# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(885, 708)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.themeGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.themeGroup.setTitle("")
        self.themeGroup.setObjectName("themeGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.themeGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.themeText = QtWidgets.QLineEdit(self.themeGroup)
        self.themeText.setFrame(True)
        self.themeText.setReadOnly(True)
        self.themeText.setObjectName("themeText")
        self.gridLayout_3.addWidget(self.themeText, 5, 0, 1, 2)
        self.themeLabel = QtWidgets.QLabel(self.themeGroup)
        self.themeLabel.setTextFormat(QtCore.Qt.AutoText)
        self.themeLabel.setObjectName("themeLabel")
        self.gridLayout_3.addWidget(self.themeLabel, 2, 0, 1, 1)
        self.themeBox = QtWidgets.QComboBox(self.themeGroup)
        self.themeBox.setObjectName("themeBox")
        self.gridLayout_3.addWidget(self.themeBox, 1, 0, 1, 2)
        self.themeLabel2 = QtWidgets.QLabel(self.themeGroup)
        self.themeLabel2.setObjectName("themeLabel2")
        self.gridLayout_3.addWidget(self.themeLabel2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.themeGroup, 1, 0, 1, 1)
        self.plotWidget = QPltWidget(self.centralwidget)
        self.plotWidget.setEnabled(True)
        self.plotWidget.setObjectName("plotWidget")
        self.gridLayout_2.addWidget(self.plotWidget, 0, 1, 3, 1)
        self.resultGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.resultGroup.setTitle("")
        self.resultGroup.setObjectName("resultGroup")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.resultGroup)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.rightLabel2 = QtWidgets.QLabel(self.resultGroup)
        self.rightLabel2.setObjectName("rightLabel2")
        self.gridLayout_4.addWidget(self.rightLabel2, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.rightList2 = QtWidgets.QListWidget(self.resultGroup)
        self.rightList2.setObjectName("rightList2")
        self.gridLayout_4.addWidget(self.rightList2, 3, 1, 1, 1)
        self.leftTable = QtWidgets.QTableWidget(self.resultGroup)
        self.leftTable.setMinimumSize(QtCore.QSize(0, 0))
        self.leftTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.leftTable.setColumnCount(2)
        self.leftTable.setObjectName("leftTable")
        self.leftTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.leftTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.leftTable.setHorizontalHeaderItem(1, item)
        self.leftTable.horizontalHeader().setVisible(True)
        self.leftTable.horizontalHeader().setCascadingSectionResizes(False)
        self.leftTable.horizontalHeader().setMinimumSectionSize(35)
        self.leftTable.horizontalHeader().setSortIndicatorShown(False)
        self.leftTable.horizontalHeader().setStretchLastSection(False)
        self.leftTable.verticalHeader().setVisible(False)
        self.leftTable.verticalHeader().setCascadingSectionResizes(False)
        self.leftTable.verticalHeader().setDefaultSectionSize(20)
        self.leftTable.verticalHeader().setMinimumSectionSize(20)
        self.leftTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout_4.addWidget(self.leftTable, 1, 0, 3, 1, QtCore.Qt.AlignLeft)
        self.leftLabel = QtWidgets.QLabel(self.resultGroup)
        self.leftLabel.setTextFormat(QtCore.Qt.AutoText)
        self.leftLabel.setObjectName("leftLabel")
        self.gridLayout_4.addWidget(self.leftLabel, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.clusterButton = QtWidgets.QPushButton(self.resultGroup)
        self.clusterButton.setMaximumSize(QtCore.QSize(108, 23))
        self.clusterButton.setObjectName("clusterButton")
        self.gridLayout_4.addWidget(self.clusterButton, 4, 1, 1, 1, QtCore.Qt.AlignRight)
        self.rightList = QtWidgets.QListWidget(self.resultGroup)
        self.rightList.setMinimumSize(QtCore.QSize(0, 0))
        self.rightList.setObjectName("rightList")
        self.gridLayout_4.addWidget(self.rightList, 1, 1, 1, 1)
        self.rightLabel = QtWidgets.QLabel(self.resultGroup)
        self.rightLabel.setTextFormat(QtCore.Qt.AutoText)
        self.rightLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rightLabel.setObjectName("rightLabel")
        self.gridLayout_4.addWidget(self.rightLabel, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout_2.addWidget(self.resultGroup, 2, 0, 1, 1)
        self.searchGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.searchGroup.setTitle("")
        self.searchGroup.setObjectName("searchGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.searchGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.searchLabel = QtWidgets.QLabel(self.searchGroup)
        self.searchLabel.setTextFormat(QtCore.Qt.AutoText)
        self.searchLabel.setObjectName("searchLabel")
        self.gridLayout.addWidget(self.searchLabel, 6, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.searchLine = QtWidgets.QLineEdit(self.searchGroup)
        self.searchLine.setObjectName("searchLine")
        self.gridLayout.addWidget(self.searchLine, 9, 0, 1, 4)
        self.searchButton = QtWidgets.QPushButton(self.searchGroup)
        self.searchButton.setMinimumSize(QtCore.QSize(125, 23))
        self.searchButton.setMaximumSize(QtCore.QSize(125, 23))
        self.searchButton.setIconSize(QtCore.QSize(16, 48))
        self.searchButton.setShortcut("")
        self.searchButton.setCheckable(False)
        self.searchButton.setDefault(False)
        self.searchButton.setFlat(False)
        self.searchButton.setObjectName("searchButton")
        self.gridLayout.addWidget(self.searchButton, 9, 4, 1, 1)
        self.searchMethod = QtWidgets.QComboBox(self.searchGroup)
        self.searchMethod.setMaximumSize(QtCore.QSize(125, 20))
        self.searchMethod.setObjectName("searchMethod")
        self.searchMethod.addItem("")
        self.searchMethod.addItem("")
        self.searchMethod.addItem("")
        self.gridLayout.addWidget(self.searchMethod, 6, 4, 1, 1)
        self.clusterMethod = QtWidgets.QComboBox(self.searchGroup)
        self.clusterMethod.setMaximumSize(QtCore.QSize(125, 20))
        self.clusterMethod.setObjectName("clusterMethod")
        self.clusterMethod.addItem("")
        self.clusterMethod.addItem("")
        self.clusterMethod.addItem("")
        self.clusterMethod.addItem("")
        self.clusterMethod.addItem("")
        self.gridLayout.addWidget(self.clusterMethod, 4, 4, 1, 1)
        self.clusterLabel = QtWidgets.QLabel(self.searchGroup)
        self.clusterLabel.setObjectName("clusterLabel")
        self.gridLayout.addWidget(self.clusterLabel, 4, 3, 1, 1, QtCore.Qt.AlignRight)
        self.label_2 = QtWidgets.QLabel(self.searchGroup)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 3, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_2.addWidget(self.searchGroup, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Medical Text Analyzer"))
        self.themeLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Ассоциации</span></p></body></html>"))
        self.themeLabel2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Группа</span></p></body></html>"))
        self.rightLabel2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Документы группы</span></p></body></html>"))
        item = self.leftTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Слово"))
        item = self.leftTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Близость"))
        self.leftLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Похожие слова</span></p></body></html>"))
        self.clusterButton.setText(_translate("MainWindow", "Показать кластеры"))
        self.rightLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Подходящие документы</span></p></body></html>"))
        self.searchLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Запрос</span></p></body></html>"))
        self.searchButton.setText(_translate("MainWindow", "Искать"))
        self.searchMethod.setItemText(0, _translate("MainWindow", "Предложению"))
        self.searchMethod.setItemText(1, _translate("MainWindow", "Статье"))
        self.searchMethod.setItemText(2, _translate("MainWindow", "Группе"))
        self.clusterMethod.setItemText(0, _translate("MainWindow", "Affinity Propagation"))
        self.clusterMethod.setItemText(1, _translate("MainWindow", "K-Means"))
        self.clusterMethod.setItemText(2, _translate("MainWindow", "Hierarchical"))
        self.clusterMethod.setItemText(3, _translate("MainWindow", "MeanShift"))
        self.clusterMethod.setItemText(4, _translate("MainWindow", "Birch"))
        self.clusterLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Кластеризовать с:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Искать по:</span></p></body></html>"))

from qpltwidget import QPltWidget
